CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE blinds (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "nameBlind" character varying(50) NOT NULL,
    "anteBlind" integer NOT NULL,
    "descriptionBlind" character varying(200) NOT NULL,
    "effectBlind" character varying(100) NOT NULL,
    "rewardBlind" integer NOT NULL,
    "imageBlind" character varying(100),
    CONSTRAINT "PK_blinds" PRIMARY KEY (id)
);

CREATE TABLE boosterpack (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "namePack" character varying(50) NOT NULL,
    "typePack" integer NOT NULL,
    "numberPack" integer NOT NULL,
    "numberChoices" integer NOT NULL,
    "numberProposition" integer NOT NULL,
    "descriptionPack" character varying(200) NOT NULL,
    "pricePack" integer NOT NULL,
    "imageBoosterpack" character varying(100),
    "TypeBoosterpack" text NOT NULL,
    CONSTRAINT "PK_boosterpack" PRIMARY KEY (id)
);

CREATE TABLE decks (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "nameDeck" character varying(50) NOT NULL,
    "descriptionDeck" character varying(200) NOT NULL,
    "imageDeck" character varying(100),
    CONSTRAINT "PK_decks" PRIMARY KEY (id)
);

CREATE TABLE editions (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "nameEdition" character varying(50) NOT NULL,
    "effectEdition" character varying(100) NOT NULL,
    "imageEdition" character varying(100),
    CONSTRAINT "PK_editions" PRIMARY KEY (id)
);

CREATE TABLE enhancedcards (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "nameEnhanced" character varying(50) NOT NULL,
    "effectEnhanced" character varying(100) NOT NULL,
    "typeEnhanced" character varying(20) NOT NULL,
    "imageEnhancedcard" character varying(100),
    CONSTRAINT "PK_enhancedcards" PRIMARY KEY (id)
);

CREATE TABLE hands (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "nameHand" character varying(50) NOT NULL,
    "baseChips" integer NOT NULL,
    "baseMult" integer NOT NULL,
    "imageHand" character varying(100),
    CONSTRAINT "PK_hands" PRIMARY KEY (id)
);

CREATE TABLE jokers (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "nameJoker" character varying(30) NOT NULL,
    "numberJoker" integer NOT NULL,
    "rarityJoker" character varying(30) NOT NULL,
    "priceJoker" integer NOT NULL,
    "typeJoker" character varying(20) NOT NULL,
    "descriptionJoker" character varying(200) NOT NULL,
    "sizeJoker" numeric(3,2),
    "hasFaceJoker" boolean NOT NULL,
    "imageJoker" character varying(100),
    CONSTRAINT "PK_jokers" PRIMARY KEY (id)
);

CREATE TABLE seals (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "nameSeal" character varying(20) NOT NULL,
    "effectSeal" character varying(50) NOT NULL,
    "typeSeal" integer NOT NULL,
    "imageSeal" character varying(100),
    CONSTRAINT "PK_seals" PRIMARY KEY (id)
);

CREATE TABLE sticker (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "nameSticker" character varying(50) NOT NULL,
    "descriptionSticker" character varying(200) NOT NULL,
    "effectSticker" character varying(50) NOT NULL,
    "imageSticker" character varying(100),
    CONSTRAINT "PK_sticker" PRIMARY KEY (id)
);

CREATE TABLE tags (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "nameTag" character varying(50) NOT NULL,
    "effectTag" character varying(200) NOT NULL,
    "imageTag" character varying(100),
    CONSTRAINT "PK_tags" PRIMARY KEY (id)
);

CREATE TABLE vouchers (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "nameVoucher" character varying(50) NOT NULL,
    "descriptionVoucher" character varying(200) NOT NULL,
    "priceVoucher" integer NOT NULL,
    "stateVoucher" boolean NOT NULL,
    "imageVoucher" character varying(100),
    CONSTRAINT "PK_vouchers" PRIMARY KEY (id)
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE cards (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "idEnhancedcard" integer,
    "nameCard" character varying(50) NOT NULL,
    "familyCard" character varying(50) NOT NULL,
    "isEnhanced" boolean NOT NULL,
    "imageCard" character varying(100),
    CONSTRAINT "PK_cards" PRIMARY KEY (id),
    CONSTRAINT "FK_cards_enhancedcards_idEnhancedcard" FOREIGN KEY ("idEnhancedcard") REFERENCES enhancedcards (id)
);

CREATE TABLE consumables (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "idHand" integer,
    "idSeal" integer,
    "idEnhancedcard" integer,
    "nameConsumable" character varying(50) NOT NULL,
    "typeConsumable" integer NOT NULL,
    "TypeOtherEffect" integer NOT NULL,
    "effectConsumable" character varying(200) NOT NULL,
    "imageConsumable" character varying(100) NOT NULL,
    CONSTRAINT "PK_consumables" PRIMARY KEY (id),
    CONSTRAINT "FK_consumables_enhancedcards_idEnhancedcard" FOREIGN KEY ("idEnhancedcard") REFERENCES enhancedcards (id),
    CONSTRAINT "FK_consumables_hands_idHand" FOREIGN KEY ("idHand") REFERENCES hands (id),
    CONSTRAINT "FK_consumables_seals_idSeal" FOREIGN KEY ("idSeal") REFERENCES seals (id)
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_cards_idEnhancedcard" ON cards ("idEnhancedcard");

CREATE UNIQUE INDEX "IX_consumables_idEnhancedcard" ON consumables ("idEnhancedcard");

CREATE UNIQUE INDEX "IX_consumables_idHand" ON consumables ("idHand");

CREATE UNIQUE INDEX "IX_consumables_idSeal" ON consumables ("idSeal");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250627162431_InitialCreate', '9.0.5');

COMMIT;

