--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2026-05-30 19:12:38

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 243 (class 1259 OID 18088)
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 18087)
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 18005)
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 18101)
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 18100)
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 18113)
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 18125)
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 18142)
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 18012)
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 18000)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 18020)
-- Name: blinds; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.blinds (
    id integer NOT NULL,
    "nameBlind" character varying(50) NOT NULL,
    "anteBlind" integer NOT NULL,
    "descriptionBlind" character varying(200) NOT NULL,
    "effectBlind" character varying(100) NOT NULL,
    "rewardBlind" integer NOT NULL,
    "imageBlind" character varying(100)
);


ALTER TABLE public.blinds OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 18019)
-- Name: blinds_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.blinds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blinds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 18026)
-- Name: boosterpack; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.boosterpack (
    id integer NOT NULL,
    "namePack" character varying(50) NOT NULL,
    "typePack" integer NOT NULL,
    "numberPack" integer NOT NULL,
    "numberChoices" integer NOT NULL,
    "numberProposition" integer NOT NULL,
    "descriptionPack" character varying(200) NOT NULL,
    "pricePack" integer NOT NULL,
    "imageBoosterpack" character varying(100),
    "TypeBoosterpack" text NOT NULL
);


ALTER TABLE public.boosterpack OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 18025)
-- Name: boosterpack_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.boosterpack ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.boosterpack_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 18155)
-- Name: cards; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cards (
    id integer NOT NULL,
    "idEnhancedcard" integer,
    "nameCard" character varying(50) NOT NULL,
    "familyCard" character varying(50) NOT NULL,
    "isEnhanced" boolean NOT NULL,
    "imageCard" character varying(100)
);


ALTER TABLE public.cards OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 18154)
-- Name: cards_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 18166)
-- Name: consumables; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.consumables (
    id integer NOT NULL,
    "idHand" integer,
    "idSeal" integer,
    "idEnhancedcard" integer,
    "nameConsumable" character varying(50) NOT NULL,
    "typeConsumable" integer NOT NULL,
    "TypeOtherEffect" integer NOT NULL,
    "effectConsumable" character varying(200) NOT NULL,
    "imageConsumable" character varying(100) NOT NULL
);


ALTER TABLE public.consumables OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 18165)
-- Name: consumables_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.consumables ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consumables_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 18034)
-- Name: decks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.decks (
    id integer NOT NULL,
    "nameDeck" character varying(50) NOT NULL,
    "descriptionDeck" character varying(200) NOT NULL,
    "imageDeck" character varying(100)
);


ALTER TABLE public.decks OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 18033)
-- Name: decks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.decks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.decks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 18040)
-- Name: editions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.editions (
    id integer NOT NULL,
    "nameEdition" character varying(50) NOT NULL,
    "effectEdition" character varying(100) NOT NULL,
    "imageEdition" character varying(100)
);


ALTER TABLE public.editions OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 18039)
-- Name: editions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.editions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.editions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 18046)
-- Name: enhancedcards; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.enhancedcards (
    id integer NOT NULL,
    "nameEnhanced" character varying(50) NOT NULL,
    "effectEnhanced" character varying(100) NOT NULL,
    "typeEnhanced" character varying(20) NOT NULL,
    "imageEnhancedcard" character varying(100)
);


ALTER TABLE public.enhancedcards OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 18045)
-- Name: enhancedcards_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.enhancedcards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enhancedcards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 18052)
-- Name: hands; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.hands (
    id integer NOT NULL,
    "nameHand" character varying(50) NOT NULL,
    "baseChips" integer NOT NULL,
    "baseMult" integer NOT NULL,
    "imageHand" character varying(100)
);


ALTER TABLE public.hands OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 18051)
-- Name: hands_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.hands ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hands_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 18058)
-- Name: jokers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jokers (
    id integer NOT NULL,
    "nameJoker" character varying(30) NOT NULL,
    "numberJoker" integer NOT NULL,
    "rarityJoker" character varying(30) NOT NULL,
    "priceJoker" integer NOT NULL,
    "typeJoker" character varying(20) NOT NULL,
    "descriptionJoker" character varying(200) NOT NULL,
    "sizeJoker" numeric(3,2),
    "hasFaceJoker" boolean NOT NULL,
    "imageJoker" character varying(100)
);


ALTER TABLE public.jokers OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 18057)
-- Name: jokers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.jokers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jokers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 18064)
-- Name: seals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.seals (
    id integer NOT NULL,
    "nameSeal" character varying(20) NOT NULL,
    "effectSeal" character varying(50) NOT NULL,
    "typeSeal" integer NOT NULL,
    "imageSeal" character varying(100)
);


ALTER TABLE public.seals OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 18063)
-- Name: seals_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.seals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 18070)
-- Name: sticker; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sticker (
    id integer NOT NULL,
    "nameSticker" character varying(50) NOT NULL,
    "descriptionSticker" character varying(200) NOT NULL,
    "effectSticker" character varying(50) NOT NULL,
    "imageSticker" character varying(100)
);


ALTER TABLE public.sticker OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 18069)
-- Name: sticker_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sticker ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sticker_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 18076)
-- Name: tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tags (
    id integer NOT NULL,
    "nameTag" character varying(50) NOT NULL,
    "effectTag" character varying(200) NOT NULL,
    "imageTag" character varying(100)
);


ALTER TABLE public.tags OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 18075)
-- Name: tags_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 18082)
-- Name: vouchers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vouchers (
    id integer NOT NULL,
    "nameVoucher" character varying(50) NOT NULL,
    "descriptionVoucher" character varying(200) NOT NULL,
    "priceVoucher" integer NOT NULL,
    "stateVoucher" boolean NOT NULL,
    "imageVoucher" character varying(100)
);


ALTER TABLE public.vouchers OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 18081)
-- Name: vouchers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.vouchers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vouchers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5070 (class 0 OID 18088)
-- Dependencies: 243
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5045 (class 0 OID 18005)
-- Dependencies: 218
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."AspNetRoles" VALUES ('abcb5b0b-d47b-487e-a418-57b0d1343fff', 'Admin', 'ADMIN', NULL);


--
-- TOC entry 5072 (class 0 OID 18101)
-- Dependencies: 245
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5073 (class 0 OID 18113)
-- Dependencies: 246
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5074 (class 0 OID 18125)
-- Dependencies: 247
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."AspNetUserRoles" VALUES ('450b5b0b-d47b-487e-a418-57b0d1343fff', 'abcb5b0b-d47b-487e-a418-57b0d1343fff');


--
-- TOC entry 5075 (class 0 OID 18142)
-- Dependencies: 248
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5046 (class 0 OID 18012)
-- Dependencies: 219
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."AspNetUsers" VALUES ('450b5b0b-d47b-487e-a418-57b0d1343fff', 'n7@graff.vk', 'N7@GRAFF.VK', 'n7@graff.vk', 'N7@GRAFF.VK', true, 'AQAAAAIAAYagAAAAEMI9ciAIcl5uF10E+1pz8y3nMito8EVomoJoPllg7wB7PpuYt0kMOIBIyLKgBcItSg==', 'NZAT67VQUTETSEIR7PEBADKUVRUJRRFC', '66df8664-d3e6-43d1-9e52-7cc8e8d42f14', NULL, false, false, NULL, true, 0);
INSERT INTO public."AspNetUsers" VALUES ('06fca5a3-82d2-4dbf-b9bd-7b84acdc1da9', 'admin@balatro.dev', 'ADMIN@BALATRO.DEV', 'admin@balatro.dev', 'ADMIN@BALATRO.DEV', true, 'AQAAAAIAAYagAAAAENiArajT2OdTV0t/jbuXip/+fwo+Cayn9ObXa6Y6B+h5hXlOY0CgeqZf8NS4UCrIRA==', 'FGBEYLLLMQAJRQAGCG2PFB3WMDBM4PD2', '55da214b-03f9-470e-adb0-81128588f318', NULL, false, false, NULL, true, 0);


--
-- TOC entry 5044 (class 0 OID 18000)
-- Dependencies: 217
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: n7
--

INSERT INTO public."__EFMigrationsHistory" VALUES ('20250627125446_InitialCreate', '9.0.5');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20250627162431_InitialCreate', '9.0.0');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260530165211_SeedAdminUserFixed', '9.0.5');


--
-- TOC entry 5048 (class 0 OID 18020)
-- Dependencies: 221
-- Data for Name: blinds; Type: TABLE DATA; Schema: public; Owner: n7
--



--
-- TOC entry 5050 (class 0 OID 18026)
-- Dependencies: 223
-- Data for Name: boosterpack; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5077 (class 0 OID 18155)
-- Dependencies: 250
-- Data for Name: cards; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5079 (class 0 OID 18166)
-- Dependencies: 252
-- Data for Name: consumables; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.consumables VALUES (1, NULL, NULL, NULL, 'Fool', 1, 2, 'Creates the last Tarot or Planet card used during this run The Fool excluded', 'Fool.webp');


--
-- TOC entry 5052 (class 0 OID 18034)
-- Dependencies: 225
-- Data for Name: decks; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5054 (class 0 OID 18040)
-- Dependencies: 227
-- Data for Name: editions; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5056 (class 0 OID 18046)
-- Dependencies: 229
-- Data for Name: enhancedcards; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5058 (class 0 OID 18052)
-- Dependencies: 231
-- Data for Name: hands; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5060 (class 0 OID 18058)
-- Dependencies: 233
-- Data for Name: jokers; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.jokers VALUES (4, 'Pareidolia', 37, 'Uncommon', 5, 'Other', 'All cards are considered face cards', 4.18, false, 'Pareidolia.webp');


--
-- TOC entry 5062 (class 0 OID 18064)
-- Dependencies: 235
-- Data for Name: seals; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5064 (class 0 OID 18070)
-- Dependencies: 237
-- Data for Name: sticker; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5066 (class 0 OID 18076)
-- Dependencies: 239
-- Data for Name: tags; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5068 (class 0 OID 18082)
-- Dependencies: 241
-- Data for Name: vouchers; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5085 (class 0 OID 0)
-- Dependencies: 242
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- TOC entry 5086 (class 0 OID 0)
-- Dependencies: 244
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- TOC entry 5087 (class 0 OID 0)
-- Dependencies: 220
-- Name: blinds_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.blinds_id_seq', 1, false);


--
-- TOC entry 5088 (class 0 OID 0)
-- Dependencies: 222
-- Name: boosterpack_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.boosterpack_id_seq', 1, false);


--
-- TOC entry 5089 (class 0 OID 0)
-- Dependencies: 249
-- Name: cards_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cards_id_seq', 1, false);


--
-- TOC entry 5090 (class 0 OID 0)
-- Dependencies: 251
-- Name: consumables_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.consumables_id_seq', 1, true);


--
-- TOC entry 5091 (class 0 OID 0)
-- Dependencies: 224
-- Name: decks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.decks_id_seq', 1, false);


--
-- TOC entry 5092 (class 0 OID 0)
-- Dependencies: 226
-- Name: editions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.editions_id_seq', 1, false);


--
-- TOC entry 5093 (class 0 OID 0)
-- Dependencies: 228
-- Name: enhancedcards_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.enhancedcards_id_seq', 1, false);


--
-- TOC entry 5094 (class 0 OID 0)
-- Dependencies: 230
-- Name: hands_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.hands_id_seq', 1, false);


--
-- TOC entry 5095 (class 0 OID 0)
-- Dependencies: 232
-- Name: jokers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.jokers_id_seq', 6, true);


--
-- TOC entry 5096 (class 0 OID 0)
-- Dependencies: 234
-- Name: seals_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.seals_id_seq', 1, false);


--
-- TOC entry 5097 (class 0 OID 0)
-- Dependencies: 236
-- Name: sticker_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sticker_id_seq', 1, false);


--
-- TOC entry 5098 (class 0 OID 0)
-- Dependencies: 238
-- Name: tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tags_id_seq', 1, false);


--
-- TOC entry 5099 (class 0 OID 0)
-- Dependencies: 240
-- Name: vouchers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.vouchers_id_seq', 1, false);


--
-- TOC entry 4869 (class 2606 OID 18094)
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 4839 (class 2606 OID 18011)
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- TOC entry 4872 (class 2606 OID 18107)
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 4875 (class 2606 OID 18119)
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 4878 (class 2606 OID 18131)
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 4880 (class 2606 OID 18148)
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 4843 (class 2606 OID 18018)
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- TOC entry 4837 (class 2606 OID 18004)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4846 (class 2606 OID 18024)
-- Name: blinds PK_blinds; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blinds
    ADD CONSTRAINT "PK_blinds" PRIMARY KEY (id);


--
-- TOC entry 4848 (class 2606 OID 18032)
-- Name: boosterpack PK_boosterpack; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.boosterpack
    ADD CONSTRAINT "PK_boosterpack" PRIMARY KEY (id);


--
-- TOC entry 4883 (class 2606 OID 18159)
-- Name: cards PK_cards; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cards
    ADD CONSTRAINT "PK_cards" PRIMARY KEY (id);


--
-- TOC entry 4888 (class 2606 OID 18170)
-- Name: consumables PK_consumables; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consumables
    ADD CONSTRAINT "PK_consumables" PRIMARY KEY (id);


--
-- TOC entry 4850 (class 2606 OID 18038)
-- Name: decks PK_decks; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.decks
    ADD CONSTRAINT "PK_decks" PRIMARY KEY (id);


--
-- TOC entry 4852 (class 2606 OID 18044)
-- Name: editions PK_editions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.editions
    ADD CONSTRAINT "PK_editions" PRIMARY KEY (id);


--
-- TOC entry 4854 (class 2606 OID 18050)
-- Name: enhancedcards PK_enhancedcards; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enhancedcards
    ADD CONSTRAINT "PK_enhancedcards" PRIMARY KEY (id);


--
-- TOC entry 4856 (class 2606 OID 18056)
-- Name: hands PK_hands; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hands
    ADD CONSTRAINT "PK_hands" PRIMARY KEY (id);


--
-- TOC entry 4858 (class 2606 OID 18062)
-- Name: jokers PK_jokers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jokers
    ADD CONSTRAINT "PK_jokers" PRIMARY KEY (id);


--
-- TOC entry 4860 (class 2606 OID 18068)
-- Name: seals PK_seals; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seals
    ADD CONSTRAINT "PK_seals" PRIMARY KEY (id);


--
-- TOC entry 4862 (class 2606 OID 18074)
-- Name: sticker PK_sticker; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sticker
    ADD CONSTRAINT "PK_sticker" PRIMARY KEY (id);


--
-- TOC entry 4864 (class 2606 OID 18080)
-- Name: tags PK_tags; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT "PK_tags" PRIMARY KEY (id);


--
-- TOC entry 4866 (class 2606 OID 18086)
-- Name: vouchers PK_vouchers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vouchers
    ADD CONSTRAINT "PK_vouchers" PRIMARY KEY (id);


--
-- TOC entry 4841 (class 1259 OID 18191)
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- TOC entry 4867 (class 1259 OID 18186)
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- TOC entry 4870 (class 1259 OID 18188)
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- TOC entry 4873 (class 1259 OID 18189)
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- TOC entry 4876 (class 1259 OID 18190)
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- TOC entry 4881 (class 1259 OID 18193)
-- Name: IX_cards_idEnhancedcard; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_cards_idEnhancedcard" ON public.cards USING btree ("idEnhancedcard");


--
-- TOC entry 4884 (class 1259 OID 18194)
-- Name: IX_consumables_idEnhancedcard; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_consumables_idEnhancedcard" ON public.consumables USING btree ("idEnhancedcard");


--
-- TOC entry 4885 (class 1259 OID 18195)
-- Name: IX_consumables_idHand; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_consumables_idHand" ON public.consumables USING btree ("idHand");


--
-- TOC entry 4886 (class 1259 OID 18196)
-- Name: IX_consumables_idSeal; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_consumables_idSeal" ON public.consumables USING btree ("idSeal");


--
-- TOC entry 4840 (class 1259 OID 18187)
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- TOC entry 4844 (class 1259 OID 18192)
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- TOC entry 4889 (class 2606 OID 18095)
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 4890 (class 2606 OID 18108)
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 4891 (class 2606 OID 18120)
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 4892 (class 2606 OID 18132)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 4893 (class 2606 OID 18137)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 4894 (class 2606 OID 18149)
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 4895 (class 2606 OID 18160)
-- Name: cards FK_cards_enhancedcards_idEnhancedcard; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cards
    ADD CONSTRAINT "FK_cards_enhancedcards_idEnhancedcard" FOREIGN KEY ("idEnhancedcard") REFERENCES public.enhancedcards(id);


--
-- TOC entry 4896 (class 2606 OID 18171)
-- Name: consumables FK_consumables_enhancedcards_idEnhancedcard; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consumables
    ADD CONSTRAINT "FK_consumables_enhancedcards_idEnhancedcard" FOREIGN KEY ("idEnhancedcard") REFERENCES public.enhancedcards(id);


--
-- TOC entry 4897 (class 2606 OID 18176)
-- Name: consumables FK_consumables_hands_idHand; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consumables
    ADD CONSTRAINT "FK_consumables_hands_idHand" FOREIGN KEY ("idHand") REFERENCES public.hands(id);


--
-- TOC entry 4898 (class 2606 OID 18181)
-- Name: consumables FK_consumables_seals_idSeal; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consumables
    ADD CONSTRAINT "FK_consumables_seals_idSeal" FOREIGN KEY ("idSeal") REFERENCES public.seals(id);


-- Completed on 2026-05-30 19:12:39

--
-- PostgreSQL database dump complete
--

