// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalatroWikiApp.Models;

public partial class Blind
{
    public int IdBlind { get; set; }

    public string NameBlind { get; set; }

    public int AnteBlind { get; set; }

    public string DescriptionBlind { get; set; }

    public string EffectBlind { get; set; }

    public int RewardBlind { get; set; }
}