// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalatroWikiApp.Models;

public partial class Boosterpack
{
    public int IdJoker { get; set; }

    public int IdTarot { get; set; }

    public int IdSpectral { get; set; }

    public int NumCard { get; set; }

    public string NamePack { get; set; }

    public int NumberPack { get; set; }

    public int NumberChoices { get; set; }

    public int NumberProposition { get; set; }

    public string DescriptionPack { get; set; }

    public int PricePack { get; set; }

    public virtual Joker IdJokerNavigation { get; set; }

    public virtual Spectralcard IdSpectralNavigation { get; set; }

    public virtual Tarotcard IdTarotNavigation { get; set; }

    public virtual Card NumCardNavigation { get; set; }
}