// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BalatroWikiApp.Models;

[Table("cards")]
[MySqlCharSet("utf8mb3")]
[MySqlCollation("utf8mb3_general_ci")]
public partial class Card
{
    [Key]
    [Column("numCard")]
    public int NumCard { get; set; }

    [Required]
    [Column("nameCard")]
    [StringLength(50)]
    public string NameCard { get; set; }

    [Required]
    [Column("familyCard")]
    [StringLength(50)]
    public string FamilyCard { get; set; }

    [Column("isEnhanced")]
    public bool IsEnhanced { get; set; }

    [InverseProperty("NumCardNavigation")]
    public virtual ICollection<Boosterpack> Boosterpacks { get; set; } = new List<Boosterpack>();
}