// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalatroWikiApp.Models;

public partial class Card
{
    public int NumCard { get; set; }

    public string NameCard { get; set; }

    public string FamilyCard { get; set; }

    public bool IsEnhanced { get; set; }

    public virtual ICollection<Boosterpack> Boosterpacks { get; set; } = new List<Boosterpack>();
}