// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BalatroWikiApp.Models;

[Table("decks")]
public partial class Deck
{
    [Key]
    [Column("idDeck")]
    public int IdDeck { get; set; }

    [Column("nameDeck")]
    [StringLength(50)]
    public string NameDeck { get; set; }

    [Column("descriptionDeck")]
    [StringLength(200)]
    public string DescriptionDeck { get; set; }
}