// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalatroWikiApp.Models;

public partial class Deck
{
    public int IdDeck { get; set; }

    public string NameDeck { get; set; }

    public string DescriptionDeck { get; set; }
}