// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalatroWikiApp.Models;

public partial class Edition
{
    public int IdEdition { get; set; }

    public string NameEdition { get; set; }

    public string EffectEdition { get; set; }
}