// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalatroWikiApp.Models;

public partial class Enhancedcard
{
    public int IdEnhanced { get; set; }

    public string NameEnhanced { get; set; }

    public string EffectEnhanced { get; set; }

    public string TypeEnhanced { get; set; }
}