// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BalatroWikiApp.Models;

[Table("enhancedcards")]
public partial class Enhancedcard
{
    [Key]
    [Column("idEnhanced")]
    public int IdEnhanced { get; set; }

    [Required]
    [Column("nameEnhanced")]
    [StringLength(50)]
    public string NameEnhanced { get; set; }

    [Required]
    [Column("effectEnhanced")]
    [StringLength(50)]
    public string EffectEnhanced { get; set; }

    [Required]
    [Column("typeEnhanced")]
    [StringLength(20)]
    public string TypeEnhanced { get; set; }
}