// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalatroWikiApp.Models;

public partial class Joker
{
    public int IdJoker { get; set; }

    public string NameJoker { get; set; }

    public string RarityJoker { get; set; }

    public int PriceJoker { get; set; }

    public string TypeJoker { get; set; }

    public string DescriptionJoker { get; set; }

    public decimal? SizeJoker { get; set; }

    public bool HasFaceJoker { get; set; }

    public virtual ICollection<Boosterpack> Boosterpacks { get; set; } = new List<Boosterpack>();
}