// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalatroWikiApp.Models;

public partial class Planetcard
{
    public int IdPlanet { get; set; }

    public string NamePlanet { get; set; }

    public string HandPlanet { get; set; }
}