// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BalatroWikiApp.Models;

[Table("planetcard")]
public partial class Planetcard
{
    [Key]
    [Column("idPlanet")]
    public int IdPlanet { get; set; }

    [Required]
    [Column("namePlanet")]
    [StringLength(50)]
    public string NamePlanet { get; set; }

    [Required]
    [Column("handPlanet")]
    [StringLength(50)]
    public string HandPlanet { get; set; }
}