// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalatroWikiApp.Models;

public partial class Seal
{
    public int IdSeal { get; set; }

    public string NameSeal { get; set; }

    public string EffectSeal { get; set; }

    public string TypeSeal { get; set; }
}