// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalatroWikiApp.Models;

public partial class Spectralcard
{
    public int IdSpectral { get; set; }

    public string NameSpectral { get; set; }

    public string EffectSpectral { get; set; }

    public virtual ICollection<Boosterpack> Boosterpacks { get; set; } = new List<Boosterpack>();
}