// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalatroWikiApp.Models;

public partial class Sticker
{
    public int IdSticker { get; set; }

    public string NameSticker { get; set; }

    public string DescriptionSticker { get; set; }

    public string EffectSticker { get; set; }
}