// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BalatroWikiApp.Models;

[Table("sticker")]
public partial class Sticker
{
    [Key]
    [Column("idSticker")]
    public int IdSticker { get; set; }

    [Required]
    [Column("nameSticker")]
    [StringLength(50)]
    public string NameSticker { get; set; }

    [Required]
    [Column("descriptionSticker")]
    [StringLength(200)]
    public string DescriptionSticker { get; set; }

    [Required]
    [Column("effectSticker")]
    [StringLength(50)]
    public string EffectSticker { get; set; }
}