// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalatroWikiApp.Models;

public partial class Tag
{
    public int IdTag { get; set; }

    public string NameTag { get; set; }

    public string EffectTag { get; set; }
}