// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BalatroWikiApp.Models;

public partial class Voucher
{
    public int IdVoucher { get; set; }

    public string NameVoucher { get; set; }

    public string DescriptionVoucher { get; set; }

    public int PriceVoucher { get; set; }

    public bool StateVoucher { get; set; }
}