// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BalatroWikiApp.Models;

[Table("vouchers")]
public partial class Voucher
{
    [Key]
    [Column("idVoucher")]
    public int IdVoucher { get; set; }

    [Required]
    [Column("nameVoucher")]
    [StringLength(50)]
    public string NameVoucher { get; set; }

    [Required]
    [Column("descriptionVoucher")]
    [StringLength(200)]
    public string DescriptionVoucher { get; set; }

    [Column("priceVoucher")]
    public int PriceVoucher { get; set; }

    [Column("stateVoucher")]
    public bool StateVoucher { get; set; }
}